[project]
name = "discord-bot"
version = "2.1.0"
description = "Yet Another Shitly Made Discord Bot."
license = "EUPL-1.2"
readme = "docs/README.md"
requires-python = ">=3.14"
dependencies = [
	"discord-py>=2.6.4",
    "discord-py[voice]>=2.6.4",
    "google-genai>=1.62.0",
    "python-dotenv>=1.2.1",
    "pyyaml>=6.0.3",
    "yt-dlp>=2026.2.4",
]


[tool.basedpyright]
typeCheckingMode = "standard"
reportOptionalMemberAccess = false
reportFunctionMemberAccess = false

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "ruff>=0.15.0",
]

[project.scripts]
bot = "main:main"

[tool.uv]
package = true

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.hatch.build.targets.wheel.sources]
"src" = ""

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

## --- RUFF ---
[tool.ruff]
target-version = "py314" #  3.14159265359!
extend-exclude = [
    "*.py.example",
]
line-length = 100
preview = true  # required for CPY001 (mandatory file header)

[tool.ruff.lint]
select = ["ALL", "CPY001"]
# Ignore specific rules if needed
ignore = [
    "S101", # Allow assert
    "S108", # Allow usage of /tmp/
    "PLR0911", # Too many return statements
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.mccabe]
max-complexity = 12

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["PLR2004"]

[tool.ruff.lint.flake8-copyright]
# Mandatory EUPL copyright + license header on every Python file (CPY001 is preview-only).
author = "hakergeniusz"
